import Head from 'next/head'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <div className='px-3 py-10 bg-[#2c2c54] '>
      <div className='min-h-screen flex items-center justify-center mx-auto'>
        <Head>
          <title>Preview Links</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Hero />
      </div>
    </div>

  )
}
